export const LOAD_SINGLE_PRODUCT_LOADING = "LOAD_SINGLE_PRODUCT_LOADING";
export const LOAD_SINGLE_PRODUCT_SUCCESS = "LOAD_SINGLE_PRODUCT_SUCCESS";
export const LOAD_SINGLE_PRODUCT_ERROR = "LOAD_SINGLE_PRODUCT_ERROR";
export const REMOVE_SINGLE_PRODUCT_ERROR = "REMOVE_SINGLE_PRODUCT_ERROR";
export const REMOVE_COLOR = "REMOVE_COLOR";
