export const LOAD_PRODUCT_GROUP_LOADING = "LOAD_PRODUCT_GROUP_LOADING";
export const LOAD_PRODUCT_GROUP_SUCCESS = "LOAD_PRODUCT_GROUP_SUCCESS";
export const LOAD_PRODUCT_GROUP_ERROR = "LOAD_PRODUCT_GROUP_ERROR";
